### ISSUE TITLE
Observers not called

### ISSUE THREAD

**Issue by cweiske** [guidocella/eloquent-insert-on-duplicate-key#5]
We are using [Observers](https://laravel.com/docs/5.5/eloquent#observers) for our models and register them in app/Providers/EventServiceProvider.php:

```
function boot()
{
    \App\Model::observe(\App\Observers\ModelObserver::class);
}
```

In our observer classes, we have methods like `created`, `creating`, `saved`, `saving`, `deleted` and `deleting` that are called when such a model event is fired.

But when using `Model::insertOnDuplicateKey()`, the "created" or "updated" observer methods are not called.

**Comment by guidocella** [comment]
Events don't fire even with the regular `insert`, which this package's macros wrap, since `Illuminate\Database\Query\Builder` has no concept of models. Only methods of `Illuminate\Database\Eloquent\Model` and `Illuminate\Database\Eloquent\Builder` like `updateOrCreate` dispatch model events.

**Comment by cweiske** [comment]
I solved my problem the following way:

```
$original = Model::find($id);
Model::insertOnDuplicateKey($data);

$new = Model::find($id);
if ($original) {
    $new->overwriteOriginal($original->attributesToArray());
    $new->syncChanges();
}
$model->fireModelEventManually('saved', false);
```

Now I can use `wasChanged()` on my model.

Both custom methods are in a trait:
```
/**
 * Provides a public method to fire model events.
 * Needed because we use insertOnDuplicateKey(), which does not fire events:
 * https://github.com/guidocella/eloquent-insert-on-duplicate-key/issues/5
 *
 * WARNING: Model's getOriginal() will not return the original data at all
 * now. We have to manually take care of this.
 *
 * @author Christian Weiske <weiske@mogic.com>
 */
trait ManualEventsTrait
{
    /**
     * Fire the given event for the model (public).
     *
     * @param string $event Event name ("saved")
     * @param bool   $halt  Stop when a callback says no.
     *
     * @return mixed
     */
    public function fireModelEventManually($event, $halt = true)
    {
        return $this->fireModelEvent($event, $halt);
    }

    /**
     * Replace the $original array with our own data
     * So we can use getOriginal() again.
     *
     * @param array $data Full original attributes
     *
     * @return void
     */
    public function overwriteOriginal(array $data)
    {
        $this->original = $data;
    }
}
?>
```

**Comment by guidocella** [comment]
I don't understand the advantage over simply using `updateOrCreate` in your example. `INSERT ON DUPLICATE KEY...UPDATE` is useful to quickly update or insert rows in a table with different values for each row and to avoid race conditions, but in your example it seems that you're operating on a single model, and are still susceptible to a race condition in which the model is created between the `find` and `insertOnDuplicateKey` calls. It even executes 3 queries instead of the 2 of `updateOrCreate`.

**Comment by cweiske** [comment]
I do have race conditions, because a second system is synchronizing changes into my API. There is no way to fix that race conditions except using "insert on duplicate key", not even with transactions (because the check if the record exists is not transacted)
